Update content_agent.py
fixing the following pre-commit errors:
autogen/agentchat/contrib/content_agent.py:21:1: E402 Module level import not at top of file
autogen/agentchat/contrib/content_agent.py:34:1: E402 Module level import not at top of file
autogen/agentchat/contrib/content_agent.py:65:33: F811 Redefinition of unused `deque` from line 6
autogen/agentchat/contrib/content_agent.py:374:26: F811 Redefinition of unused `filename` from line 7